import { createElement } from 'lwc';
import Jesttestcomponent from 'c/jesttestcomponent';

describe('c-jesttestcomponent', () => {

    beforeEach(()=>{
        const element = createElement('c-jesttestcomponent', {
            is: Jesttestcomponent
        });
        document.body.appendChild(element);
    });
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    async function flushPromises(){
        return Promise.resolve();
    }
    it('TODO: test case generated by CLI command, please fill in test logic', async () => {
        // Arrange
        // const element = createElement('c-jesttestcomponent', {
        //     is: Jesttestcomponent
        // });

        // // Act
        // document.body.appendChild(element);
        const element = document.body.firstChild;
        let input = element.shadowRoot.querySelector('lightning-input');
        input.value="test";

        let btn = element.shadowRoot.querySelector('lightning-button');
        expect(btn.label).toBe("Click to display your message");
        btn.click();

        await flushPromises();

        expect(element.shadowRoot.querySelector('div').textContent).toBe('test');
        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });

    
});